/**
 * One-shot extraction of the static ASCII art + audio URL out of the original
 * hand-written page (`legacy/index.html`) into `src/data/art.js`.
 *
 * The art is content, not code: it stays plain so the build keeps it readable in
 * dev. Run `node scripts/gen-art.mjs` only if `legacy/index.html` changes.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const html = readFileSync(resolve(root, 'legacy/index.html'), 'utf8')

function between(startTag, endTag, from = 0) {
  const s = html.indexOf(startTag, from)
  if (s < 0) throw new Error(`missing ${startTag}`)
  const a = s + startTag.length
  const b = html.indexOf(endTag, a)
  if (b < 0) throw new Error(`missing ${endTag}`)
  return html.slice(a, b)
}

const bgart = between('<pre id="bgart" class="art" aria-hidden="true">', '</pre>')
const blart = between(
  '<pre id="blart" class="art" aria-hidden="true">',
  '</pre>',
  html.indexOf('<pre id="blart"'),
)
const enterart = between('<pre id="enterart" class="art">', '</pre>', html.indexOf('<pre id="enterart"'))
const bgmSrc = /<audio id="bgm" src="([^"]+)"/.exec(html)[1].replace(/&amp;/g, '&')

const bannerSrc = between('var ART=[', '];', html.indexOf('var ART=['))
const banner = Function(`"use strict";return [${bannerSrc}]`)()

const out = `// GENERATED by scripts/gen-art.mjs from legacy/index.html - do not hand edit
export const BANNER_ART = ${JSON.stringify(banner)}

export const BG_ART = ${JSON.stringify(bgart.replace(/\n+$/, ''))}

export const BL_ART = ${JSON.stringify(blart.replace(/\n+$/, ''))}

export const ENTER_ART = ${JSON.stringify(enterart.replace(/\n+$/, ''))}

export const BGM_SRC = ${JSON.stringify(bgmSrc)}
`

writeFileSync(resolve(root, 'src/data/art.js'), out)
console.log(
  `art.js written: banner ${banner.length} rows, bg ${bgart.length}B, bl ${blart.length}B, enter ${enterart.length}B`,
)
